### ISSUE TITLE
Spell Checking for plain text files

### ISSUE THREAD

**Issue by albar965** [CJCombrink/SpellChecker-Plugin#113] opened 2020-08-10 10:53 UTC
Maybe I'm missing something but is there a way to check files like `README.txt` or `CHANGELOG.txt` which are usually part of a project?

I'd consider this more useful than checking C++ comments.

Thanks for a great plugin and for the Linux support!

**Comment by CJCombrink** [comment] 2020-09-07 20:38
Unfortunately the plugin is only checking C++ sources and headers.
In the past it did by accident check other files as well, but caused a lot of issues thus I fixed the issue to only check C++ files. 

I am closing this since this is by design. I don't see this as being a priority. 
For me a bigger priority would be to handle Qml but not sure when this will happen.

**Closed by CJCombrink** 2020-09-07 20:38 UTC
