### ISSUE TITLE
Doesn't work with Hunspell 1.3.3

### ISSUE THREAD

**Issue by djurodrljaca** [CJCombrink/SpellChecker-Plugin#51] opened 2015-12-18 12:10 UTC
I tried the plugin on openSUSE Tumbleweed which is using Hunspell 1.3.3 and basically it marked all words as incorrectly spelled.

I did notice the TODO "Update to Hunspell 1.3.3" in the README file, which made me try to downgrade to Hunspell 1.3.2. After that it started working correctly.

I decided to open this issue in case someone else has the same problems as I had so that this workaround can be found a little easier.

Maybe document that the pre-built plugins require a specific Hunspell version (1.3.2)?

**Comment by CJCombrink** [comment] 2015-12-18 21:00
@djurodrljaca 

It is interesting to hear that it does not work with Hunspell 1.3.3 on a Linux/Unix based computer.

I am not in a position to test this since I do not want to "break" my development environment which uses 1.3.2 unfortunately, but I will definitely look into this (for *nix based systems). 

The TODO actually refers to updating my Windows build to use 1.3.3. I tried previously but could not get 1.3.3 build using MSVC. I gave up after struggling a while since I could build 1.3.2 without issues and it was good enough. 

I spend some time on this before the next release and if I can not make progress I will at least make it more clear that version 1.3.2 is needed. This will most probably only happen next year.

Thank you for using the plugin and taking the time to notify me (and possibly others) of this issue.

**Comment by djurodrljaca** [comment] 2015-12-19 20:30
I was about to test if i get some output on the console when I try using the plugin with Hunspell 1.3.3 ... but for some reason it works now :)

I have no idea what is different now, but it appears that it now works with the same version as I had originally...

I will let you know if I see any more problems.

**Comment by astillich** [comment] 2016-10-13 13:05
Just wanted to report that it works fine for me using hunspell 1.4.1 on Linux.

**Comment by CJCombrink** [comment] 2017-07-06 21:06
Closing since I couldn't reproduce and it seems like everything is working with the latest versions of the plugin with Hunspell 1.4.0

**Closed by CJCombrink** 2017-07-06 21:06 UTC
